@TFG_FranciscoCarreroCarrero_7WondersArchitects_Server_HostAddress = http://localhost:5222

GET {{TFG_FranciscoCarreroCarrero_7WondersArchitects_Server_HostAddress}}/weatherforecast/
Accept: application/json

###
